apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: duck2
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-duck
  template:
    metadata:
      labels:
        app: apache-duck
    spec:
      containers:
      - name: apache-duck
        image: 311724524637.dkr.ecr.ap-northeast-2.amazonaws.com/hello:1
        ports:
        - containerPort: 80

