apiVersion: v1
kind: Service
metadata:
  name: test-front
  namespace: duck2
  labels:
    env: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-044a583ed9e6a8633,subnet-0686870db4e7adf4e
spec:
  type: LoadBalancer
  selector:
    app: apache-duck
  ports:
    - port: 80

